<?
$embx_currency_default_option = array(
	'CURRENCY_AUTO_UPDATE_PERIOD' => '9:00',
	'CURRENCY_AUTO_UPDATE' => 1,
	'CURRENCY_AUTO_START_DATE' => '',
	'CURRENCY_AUTO_CURRENCIES' => 'USD:USD:0,EUR:EUR:0',
	'CURRENCY_AUTO_ROUND' => 0,
	'CURRENCY_AUTO_ROUND_DIGIT' => 0,
	'CURRENCY_AUTO_TOMORROW' => "N",
	'CURRENCY_AUTO_UCACHE_PERIOD' => '10:00',
	'CURRENCY_AUTO_UCACHE' => 0,
);
